on: push

jobs:
  producer:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a test artifact" > logfile
      - uses: actions/upload-artifact@v4
        with:
          name: my-cool-artifact
          path: logfile
  consumer:
    needs:
      - producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            console.log(`No filter: ${response}`);

            const response_filtered = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              name: "my-cool-artifact"
            });
            console.log(`No filter: ${response_filtered}`);
